server:
  port: 4444
spring:
  application:
    name: feign-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
management:
  security:
    enabled: false
feign:
  hystrix:
    enabled: true