server:
  port: 1111
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:1111/eureka
management:
  security:
    enabled: false
security:
  basic:
    enabled: false