server:
  port: 5555
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liweijian199011/configRepository.git
          search-paths: /
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka