server:
  port: 2223
spring:
  application:
    name: compute-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false